db:
  kkennibdb: 'postgresql://kkennibdb_owner:npg_jkHrWBdgzp24@ep-muddy-lake-a1424rms-pooler.ap-southeast-1.aws.neon.tech/kkennibdb?sslmode=require'

s3:
  bucket_name: 'kkennib-s3'
  region: 'ap-northeast-2'

rpc:
  mng-host:
    address: '127.0.0.1'
    port: 50153

  manager:
    address: '127.0.0.1'
    port: 50153

  ass-host:
    address: '127.0.0.1'
    port: 50156

  assistant:
    -
      address: '127.0.0.1'
      port: 50156
      workers: [1000, 2000, 3000]


wait_running_time_seconds: 50
chrome_driver_path: "./chromedriver"

naver:
  web:
    delay_time: 10
    max_count: 100
    unit_count: 15

  news:
    delay_time: 10
    max_count: 100
    unit_count: 10

  blog:
    delay_time: 10
    max_count: 100

  cafe:
    delay_time: 100
    max_count: 1000

  academic:
    delay_time: 10  #ACADEMIC_DELAY
    max_count: 1000    #MAX_ACADEMIC_COUNT
    out_max_count: 5   #ACADEMIC_OUT_MAX_COUNT
    unit_count: 10     #ACADEMIC_UNIT_COUNT
    use_cookie_jar: True
  
  scrap_data_save_path: "/data/crawler/file_naver_data"
  alias: 'naver'
  penalty_delay_time: 300